export type ServiceIcon =
  | 'oil' | 'timing' | 'geometry' | 'tires' | 'climate' | 'diagnostics'
  | 'inspection' | 'towbar' | 'windshield' | 'gearbox' | 'towing' | 'engine' | 'lights';

export type Service = {
  slug: string;
  title: string;
  short: string;
  intro: string;
  details: string[];
  image: string;
  imageAlt: string;
  icon: ServiceIcon;
};

export const services: Service[] = [
  { slug: 'vymena-oleja-a-filtrov', title: 'Výmena oleja a filtrov', short: 'Pravidelná údržba pre spoľahlivý a pokojný chod motora.', intro: 'Motorový olej a filtre patria medzi najdôležitejšie položky pravidelného servisu. Vymeníme ich podľa potrieb vášho vozidla a skontrolujeme základný stav auta.', details: ['Výmena motorového oleja', 'Výmena olejového, vzduchového, palivového a kabínového filtra', 'Základná vizuálna kontrola vozidla'], image: '/images/service-oil.webp', imageAlt: 'Vozidlo pripravené na výmenu oleja a filtrov', icon: 'oil' },
  { slug: 'kompletne-rozvody', title: 'Kompletné rozvody', short: 'Odborná výmena rozvodovej sústavy podľa typu vozidla.', intro: 'Výmenu rozvodov riešime komplexne a s ohľadom na konkrétny motor. Pred servisom preveríme potrebný rozsah a odporučíme vhodný postup.', details: ['Kontrola stavu rozvodovej sústavy', 'Výmena potrebných komponentov', 'Kontrola po montáži'], image: '/images/service-maintenance.webp', imageAlt: 'Vozidlo na zdviháku počas servisu rozvodov', icon: 'timing' },
  { slug: 'geometria-3d', title: 'Geometria 3D', short: 'Presné meranie a nastavenie geometrie náprav na počkanie.', intro: 'Správne nastavená geometria pomáha rovnomernému opotrebovaniu pneumatík a istému správaniu vozidla. Používame moderné 3D meranie, ktoré u nás zvládneme na počkanie približne za 30 minút. Cena sa odvíja od typu vozidla.', details: ['Presné zmeranie geometrie', 'Nastavenie náprav podľa možností vozidla', 'Hotové približne za 30 minút', 'Cena podľa typu vozidla'], image: '/images/service-geometry.webp', imageAlt: 'Vozidlo počas merania 3D geometrie náprav', icon: 'geometry' },
  { slug: 'pneuservis-a-vyvazovanie', title: 'Pneuservis a vyvažovanie', short: 'Prezutie, kontrola a presné vyváženie kolies.', intro: 'Postaráme sa o sezónne prezutie aj kontrolu kolies. Správne vyváženie znižuje vibrácie a prispieva ku komfortnej jazde.', details: ['Demontáž a montáž pneumatík', 'Vyvažovanie kolies', 'Kontrola pneumatík a diskov'], image: '/images/service-tires.webp', imageAlt: 'Zariadenia na prezúvanie a vyvažovanie kolies', icon: 'tires' },
  { slug: 'klimatizacia', title: 'Klimatizácia', short: 'Plnenie, dezinfekcia a opravy klimatizácie pre všetky typy vozidiel.', intro: 'Skontrolujeme funkciu klimatizácie, doplníme náplň a podľa potreby vydezinfikujeme alebo opravíme systém. Plnenie aj dezinfekciu robíme na počkanie, pričom naplnenie klimatizácie trvá približne hodinu.', details: ['Kontrola funkcie klimatizácie', 'Plnenie klimatizácie približne za hodinu', 'Dezinfekcia klimatizačného systému', 'Opravy klimatizačných zariadení pre všetky typy vozidiel'], image: '/images/air-conditioning.webp', imageAlt: 'Servis klimatizácie vozidla', icon: 'climate' },
  { slug: 'diagnostika-motora-a-elektroniky', title: 'Diagnostika motora a elektroniky', short: 'Rýchle hľadanie príčin porúch pomocou diagnostiky.', intro: 'Diagnostika pomáha presnejšie určiť zdroj problému v motore a elektronických systémoch. Výsledok s vami zrozumiteľne prejdeme.', details: ['Načítanie chybových hlásení', 'Kontrola motora a elektronických systémov', 'Návrh ďalšieho postupu'], image: '/images/service-diagnostics.webp', imageAlt: 'Diagnostika elektronických systémov vozidla', icon: 'diagnostics' },
  { slug: 'kontrola-vozidla', title: 'Všeobecná kontrola vozidla', short: 'Prehľad dôležitých častí auta pred cestou či servisom.', intro: 'Vozidlo prezrieme a upozorníme vás na viditeľné opotrebovanie alebo problémy, ktoré si zaslúžia ďalšiu pozornosť.', details: ['Kontrola základných prevádzkových častí', 'Vizuálna kontrola podvozka', 'Odporúčanie potrebného servisu'], image: '/images/service-inspection.webp', imageAlt: 'Všeobecná kontrola vozidla na zdviháku', icon: 'inspection' },
  { slug: 'montaz-taznych-zariadeni', title: 'Montáž ťažných zariadení', short: 'Profesionálna montáž ťažného zariadenia na vozidlo.', intro: 'Pomôžeme s vhodným riešením pre vaše vozidlo a zabezpečíme odbornú montáž ťažného zariadenia.', details: ['Výber riešenia podľa vozidla', 'Montáž mechanických častí', 'Zapojenie a kontrola funkcie'], image: '/images/service-towbar-private.webp', imageAlt: 'Ťažné zariadenie namontované na úžitkovom vozidle', icon: 'towbar' },
  { slug: 'vymena-celnych-skiel', title: 'Výmena čelných skiel', short: 'Bezpečná výmena poškodeného čelného skla.', intro: 'Poškodené čelné sklo riešime výmenou vhodného dielu a dôslednou montážou, aby vozidlo mohlo opäť bezpečne slúžiť.', details: ['Posúdenie poškodenia', 'Demontáž poškodeného skla', 'Montáž nového čelného skla'], image: '/images/service-windshield.webp', imageAlt: 'Manipulácia s čelným sklom pomocou servisných prísaviek', icon: 'windshield' },
  { slug: 'dsg-a-opravy-prevodoviek', title: 'DSG a opravy prevodoviek', short: 'Servis DSG aj riešenie problémov s prevodovkami.', intro: 'Pri problémoch s radením najprv preveríme stav prevodovky a navrhneme primeraný servis alebo opravu.', details: ['Diagnostika problémov s radením', 'Servis DSG prevodoviek', 'Opravy prevodoviek podľa zisteného stavu'], image: '/images/workshop-interior.webp', imageAlt: 'Servis vozidla v autoservise Original Cars', icon: 'gearbox' },
  { slug: 'odtahova-sluzba', title: 'Odťahová služba', short: 'Pomoc s prepravou nepojazdného vozidla do servisu.', intro: 'Keď sa vozidlo nevie dostať do servisu vlastnou silou, dohodneme s vami možnosti odťahu a ďalší postup.', details: ['Dohoda odťahu telefonicky', 'Preprava vozidla do servisu', 'Nadväzujúca kontrola vozidla'], image: '/images/service-towing.webp', imageAlt: 'Servisné vozidlo Original Cars pre odťahovú službu', icon: 'towing' },
  { slug: 'dekarbonizacia-bg-a-prisady', title: 'BG produkty a dekarbonizácia', short: 'Oficiálny predaj a distribúcia produktov BG pre motory, prevodovky a palivové systémy.', intro: 'Original Cars je oficiálnym predajcom a distribútorom produktov značky BG. Ponúkame široké portfólio prípravkov pre benzínové aj dieselové motory, motorové a prevodové oleje, automatické prevodovky a palivové systémy.', details: ['Prísady do motorových olejov', 'Prísady do prevodových olejov', 'Produkty a oleje do automatických prevodoviek', 'Prísady do benzínu a nafty', 'Produkty na čistenie palivového systému', 'Dekarbonizácia benzínových motorov', 'Dekarbonizácia dieselových motorov'], image: '/images/bg-products-7509.webp', imageAlt: 'Portfólio produktov značky BG v predajni Original Cars', icon: 'engine' },
  { slug: 'nastavenie-svetlometov', title: 'Nastavenie svetlometov', short: 'Presné nastavenie svetlometov za 15 €.', intro: 'Správne nastavené svetlomety zlepšujú výhľad vodiča a zároveň neoslňujú ostatných účastníkov premávky. Cena nastavenia je 15 €.', details: ['Kontrola smerovania svetlometov', 'Nastavenie výšky a sklonu', 'Cena nastavenia 15 €'], image: '/images/service-lights.webp', imageAlt: 'Meranie a nastavenie svetlometov vozidla', icon: 'lights' },
];

export const getService = (slug: string) => services.find((service) => service.slug === slug);
