export type ServiceIcon =
  | 'oil' | 'timing' | 'geometry' | 'tires' | 'climate' | 'diagnostics'
  | 'inspection' | 'towbar' | 'windshield' | 'gearbox' | 'towing' | 'engine' | 'lights';

export type Service = {
  slug: string;
  title: string;
  short: string;
  intro: string;
  secondary?: string;
  details: string[];
  image: string;
  imageAlt: string;
  icon: ServiceIcon;
  imageFit?: 'cover' | 'contain';
};

export const services: Service[] = [
  { slug: 'vymena-oleja-a-filtrov', title: 'Výmena oleja a filtrov', short: 'Pravidelná údržba s bezplatnou kontrolou podvozku, bŕzd a osvetlenia.', intro: 'Motorový olej a filtre patria medzi najdôležitejšie položky pravidelného servisu. Súčasťou každej výmeny oleja a filtrov v našom servise je aj kontrola podvozku, bŕzd a osvetlenia vášho vozidla – bezplatne.', details: ['Výmena motorového oleja', 'Výmena olejového, vzduchového, palivového a kabínového filtra', 'Bezplatná kontrola podvozku', 'Bezplatná kontrola bŕzd a osvetlenia vozidla'], image: '/images/service-oil.webp', imageAlt: 'Vozidlo pripravené na výmenu oleja a filtrov', icon: 'oil' },
  { slug: 'kompletne-rozvody', title: 'Kompletné rozvody', short: 'Odborná výmena rozvodovej sústavy podľa typu vozidla.', intro: 'Výmenu rozvodov riešime komplexne a s ohľadom na konkrétny motor. Pred servisom preveríme potrebný rozsah a odporučíme vhodný postup.', details: ['Kontrola stavu rozvodovej sústavy', 'Výmena potrebných komponentov', 'Kontrola po montáži'], image: '/images/service-maintenance.webp', imageAlt: 'Vozidlo na zdviháku počas servisu rozvodov', icon: 'timing' },
  { slug: 'geometria-3d', title: '3D geometria Hunter', short: 'Najvyššia rada Hunter HawkEye Elite – presne a na počkanie.', intro: 'Disponujeme najmodernejšou 3D geometriou Hunter HawkEye Elite – najvyššou radou technológie Hunter. Geometriu zmeriame a nastavíme na počkanie približne za 30 minút. Cena sa odvíja od typu vozidla.', details: ['Štyri kamery s vysokým rozlíšením', 'Rýchla montáž terčov bez poškodenia drahých ráfikov', 'Presné nastavenie geometrie v plnom rozsahu', 'Hotové približne za 30 minút', 'Cena podľa typu vozidla'], image: '/images/hero-geometry.webp', imageAlt: 'Vozidlo počas merania 3D geometrie Hunter HawkEye Elite', icon: 'geometry' },
  { slug: 'pneuservis-a-vyvazovanie', title: 'Komplexný pneuservis', short: 'Kompletné prezutie, kontrola a presné vyváženie kolies.', intro: 'Postaráme sa o sezónne prezutie aj kompletnú kontrolu kolies. Správne vyváženie znižuje vibrácie a prispieva ku komfortnej a bezpečnej jazde.', details: ['Demontáž a montáž pneumatík', 'Presné vyvažovanie kolies', 'Kontrola pneumatík a diskov'], image: '/images/service-tires.webp', imageAlt: 'Zariadenia na prezúvanie a vyvažovanie kolies', icon: 'tires' },
  { slug: 'klimatizacia', title: 'Kompletný servis a údržba klimatizácie', short: 'Plnenie, dezinfekcia a opravy klimatizácie pre všetky typy vozidiel.', intro: 'Poskytujeme kompletný servis, údržbu a opravy klimatizačných zariadení pre všetky typy vozidiel. Používame všetky bežné typy chladív vrátane R134a a R1234yf.', details: ['Kontrola funkcie klimatizácie', 'Plnenie klimatizácie približne za hodinu', 'Chladivá R134a a R1234yf', 'Dezinfekcia klimatizačného systému', 'Opravy klimatizačných zariadení pre všetky typy vozidiel'], image: '/images/air-conditioning.webp', imageAlt: 'Kompletný servis klimatizácie vozidla', icon: 'climate' },
  { slug: 'diagnostika-motora-a-elektroniky', title: 'Diagnostika motora a elektroniky', short: 'Najmodernejšia diagnostika pre všetky typy vozidiel.', intro: 'Disponujeme najmodernejšou diagnostikou na všetky typy vozidiel. Pomocou profesionálneho vybavenia presne určíme zdroj problému v motore a elektronických systémoch a výsledok s vami zrozumiteľne prejdeme.', details: ['Načítanie a vyhodnotenie chybových hlásení', 'Kontrola motora a elektronických systémov', 'Diagnostika osobných aj úžitkových vozidiel', 'Návrh ďalšieho postupu'], image: '/images/service-diagnostics-client.jpg', imageAlt: 'Moderné diagnostické zariadenia Original Cars pre všetky typy vozidiel', icon: 'diagnostics' },
  { slug: 'kontrola-vozidla', title: 'Všeobecná kontrola vozidla', short: 'Prehľad dôležitých častí auta pred cestou či servisom.', intro: 'Vozidlo prezrieme a upozorníme vás na viditeľné opotrebovanie alebo problémy, ktoré si zaslúžia ďalšiu pozornosť.', details: ['Kontrola základných prevádzkových častí', 'Vizuálna kontrola podvozka', 'Odporúčanie potrebného servisu'], image: '/images/service-inspection.webp', imageAlt: 'Všeobecná kontrola vozidla na zdviháku', icon: 'inspection' },
  { slug: 'montaz-taznych-zariadeni', title: 'Montáž ťažných zariadení', short: 'Partnerský predajca, odborná montáž a servis ťažných zariadení.', intro: 'Servisujeme a montujeme ťažné zariadenia všetkých typov pre všetky typy osobných a úžitkových vozidiel.', secondary: 'Pomôžeme vám vybrať vhodné riešenie pre konkrétne vozidlo a zabezpečíme odbornú montáž aj kontrolu funkcie.', details: ['Zinkované ťažné zariadenia', 'Partnerský predajca a odborná montáž', 'Montáž mechanických a elektrických častí', 'Servis a kontrola funkcie'], image: '/images/service-towbar-galia.jpg', imageAlt: 'Plagát Galia – zinkované ťažné zariadenia, partnerský predajca a odborná montáž', icon: 'towbar', imageFit: 'contain' },
  { slug: 'vymena-celnych-skiel', title: 'Výmena čelných skiel', short: 'Bezpečná výmena poškodeného čelného skla.', intro: 'Poškodené čelné sklo riešime výmenou vhodného dielu a dôslednou montážou, aby vozidlo mohlo opäť bezpečne slúžiť.', details: ['Posúdenie poškodenia', 'Demontáž poškodeného skla', 'Montáž nového čelného skla'], image: '/images/service-windshield.webp', imageAlt: 'Manipulácia s čelným sklom pomocou servisných prísaviek', icon: 'windshield' },
  { slug: 'dsg-a-opravy-prevodoviek', title: 'DSG a opravy prevodoviek', short: 'Kompletný servis, údržba a opravy automatických prevodoviek.', intro: 'Poskytujeme kompletný servis, údržbu a opravy všetkých typov automatických prevodoviek so zárukou použitia originálnych náhradných dielov vrátane prevádzkových olejov a filtrov určených pre automatické prevodovky.', secondary: 'Pri problémoch s radením najprv preveríme stav prevodovky a navrhneme primeraný servis alebo opravu.', details: ['Diagnostika problémov s radením', 'Servis DSG a všetkých typov automatických prevodoviek', 'Originálne náhradné diely', 'Originálne prevádzkové oleje a filtre', 'Opravy podľa zisteného stavu'], image: '/images/service-automatic-transmission.jpg', imageAlt: 'Moderná automatická prevodovka pripravená na odborný servis', icon: 'gearbox' },
  { slug: 'odtahova-sluzba', title: 'Odťahová služba', short: 'Odťah vozidiel do 3,5 tony v rámci celej Európskej únie.', intro: 'Odťahujeme všetky typy vozidiel do celkovej hmotnosti 3,5 tony v rámci celej Európskej únie. Pomôžeme vám aj pri poruche počas dovolenky.', details: ['Odťah všetkých typov vozidiel do 3,5 tony', 'Odťah v rámci celej Európskej únie', 'Odťah vozidla aj z dovolenky', 'Preprava posádky vozidla – maximálne 9 osôb', 'Dohoda a koordinácia odťahu telefonicky'], image: '/images/service-towing.webp', imageAlt: 'Servisné vozidlo Original Cars pre odťahovú službu', icon: 'towing' },
  { slug: 'dekarbonizacia-bg-a-prisady', title: 'BG produkty a dekarbonizácia', short: 'Oficiálny predaj a distribúcia produktov BG pre motory, prevodovky a palivové systémy.', intro: 'Original Cars je oficiálnym predajcom a distribútorom produktov značky BG. Ponúkame široké portfólio prípravkov pre benzínové aj dieselové motory, motorové a prevodové oleje, automatické prevodovky a palivové systémy.', details: ['Prísady do motorových olejov', 'Prísady do prevodových olejov', 'Produkty a oleje do automatických prevodoviek', 'Prísady do benzínu a nafty', 'Produkty na čistenie palivového systému', 'Dekarbonizácia benzínových motorov', 'Dekarbonizácia dieselových motorov'], image: '/images/bg-products-7509.webp', imageAlt: 'Portfólio produktov značky BG v predajni Original Cars', icon: 'engine' },
  { slug: 'nastavenie-svetlometov', title: 'Nastavenie svetlometov', short: 'Presné nastavenie všetkých typov svetlometov.', intro: 'Nastavujeme svetlomety všetkých typov. Správne nastavené svetlomety zlepšujú výhľad vodiča a zároveň neoslňujú ostatných účastníkov premávky.', details: ['Kontrola smerovania svetlometov', 'Nastavenie výšky a sklonu', 'Nastavenie všetkých typov svetlometov'], image: '/images/service-lights.webp', imageAlt: 'Meranie a nastavenie svetlometov vozidla', icon: 'lights' },
];

export const geometryFeatures = [
  { title: 'QuickComp™', text: 'Kompenzuje všetky kolesá a zaznamená počiatočné meranie jediným plynulým pohybom vozidla.' },
  { title: 'WinToe®', text: 'Pomáha nastaviť zbiehavosť tak, aby bol volant po každom nastavení presne vycentrovaný.' },
  { title: 'ExpressAlign®', text: 'Analyzuje konkrétne vozidlo a navrhne optimálne poradie úkonov s minimom potrebných krokov.' },
  { title: 'HawkEye Elite®', text: 'Štyri kamery s vysokým rozlíšením zabezpečujú rýchle a presné meranie geometrie v celom rozsahu.' },
];

export const getService = (slug: string) => services.find((service) => service.slug === slug);
