export type ServiceIcon =
  | 'oil' | 'timing' | 'geometry' | 'tires' | 'climate' | 'diagnostics'
  | 'inspection' | 'towbar' | 'windshield' | 'gearbox' | 'towing' | 'engine' | 'lights';

export type Service = {
  slug: string;
  title: string;
  short: string;
  intro: string;
  details: string[];
  image: string;
  imageAlt: string;
  icon: ServiceIcon;
};

export const services: Service[] = [
  { slug: 'vymena-oleja-a-filtrov', title: 'Výmena oleja a filtrov', short: 'Pravidelná údržba pre spoľahlivý a pokojný chod motora.', intro: 'Motorový olej a filtre patria medzi najdôležitejšie položky pravidelného servisu. Vymeníme ich podľa potrieb vášho vozidla a skontrolujeme základný stav auta.', details: ['Výmena motorového oleja', 'Výmena olejového, vzduchového, palivového a kabínového filtra', 'Základná vizuálna kontrola vozidla'], image: '/images/workshop-interior.webp', imageAlt: 'Dielňa autoservisu Original Cars', icon: 'oil' },
  { slug: 'kompletne-rozvody', title: 'Kompletné rozvody', short: 'Odborná výmena rozvodovej sústavy podľa typu vozidla.', intro: 'Výmenu rozvodov riešime komplexne a s ohľadom na konkrétny motor. Pred servisom preveríme potrebný rozsah a odporučíme vhodný postup.', details: ['Kontrola stavu rozvodovej sústavy', 'Výmena potrebných komponentov', 'Kontrola po montáži'], image: '/images/workshop-interior.webp', imageAlt: 'Servis vozidla v dielni Original Cars', icon: 'timing' },
  { slug: 'geometria-3d', title: 'Geometria 3D', short: 'Presné meranie a nastavenie geometrie náprav.', intro: 'Správne nastavená geometria pomáha rovnomernému opotrebovaniu pneumatík a istému správaniu vozidla. Používame moderné 3D meranie.', details: ['Presné zmeranie geometrie', 'Nastavenie náprav podľa možností vozidla', 'Kontrola výsledných hodnôt'], image: '/images/geometry-car.webp', imageAlt: 'Vozidlo počas merania 3D geometrie', icon: 'geometry' },
  { slug: 'pneuservis-a-vyvazovanie', title: 'Pneuservis a vyvažovanie', short: 'Prezutie, kontrola a presné vyváženie kolies.', intro: 'Postaráme sa o sezónne prezutie aj kontrolu kolies. Správne vyváženie znižuje vibrácie a prispieva ku komfortnej jazde.', details: ['Demontáž a montáž pneumatík', 'Vyvažovanie kolies', 'Kontrola pneumatík a diskov'], image: '/images/geometry-equipment.webp', imageAlt: 'Moderné vybavenie autoservisu', icon: 'tires' },
  { slug: 'klimatizacia', title: 'Klimatizácia', short: 'Plnenie a dezinfekcia klimatizácie v jednom servise.', intro: 'Skontrolujeme funkciu klimatizácie, doplníme náplň a podľa potreby vydezinfikujeme systém pre čistejší vzduch v interiéri.', details: ['Kontrola funkcie klimatizácie', 'Plnenie klimatizácie', 'Dezinfekcia klimatizačného systému'], image: '/images/air-conditioning.webp', imageAlt: 'Servis klimatizácie vozidla', icon: 'climate' },
  { slug: 'diagnostika-motora-a-elektroniky', title: 'Diagnostika motora a elektroniky', short: 'Rýchle hľadanie príčin porúch pomocou diagnostiky.', intro: 'Diagnostika pomáha presnejšie určiť zdroj problému v motore a elektronických systémoch. Výsledok s vami zrozumiteľne prejdeme.', details: ['Načítanie chybových hlásení', 'Kontrola motora a elektronických systémov', 'Návrh ďalšieho postupu'], image: '/images/geometry-equipment.webp', imageAlt: 'Diagnostické vybavenie v autoservise', icon: 'diagnostics' },
  { slug: 'kontrola-vozidla', title: 'Všeobecná kontrola vozidla', short: 'Prehľad dôležitých častí auta pred cestou či servisom.', intro: 'Vozidlo prezrieme a upozorníme vás na viditeľné opotrebovanie alebo problémy, ktoré si zaslúžia ďalšiu pozornosť.', details: ['Kontrola základných prevádzkových častí', 'Vizuálna kontrola podvozka', 'Odporúčanie potrebného servisu'], image: '/images/workshop-interior.webp', imageAlt: 'Kontrola vozidla na zdviháku', icon: 'inspection' },
  { slug: 'montaz-taznych-zariadeni', title: 'Montáž ťažných zariadení', short: 'Profesionálna montáž ťažného zariadenia na vozidlo.', intro: 'Pomôžeme s vhodným riešením pre vaše vozidlo a zabezpečíme odbornú montáž ťažného zariadenia.', details: ['Výber riešenia podľa vozidla', 'Montáž mechanických častí', 'Zapojenie a kontrola funkcie'], image: '/images/workshop-interior.webp', imageAlt: 'Montáž príslušenstva na vozidlo', icon: 'towbar' },
  { slug: 'vymena-celnych-skiel', title: 'Výmena čelných skiel', short: 'Bezpečná výmena poškodeného čelného skla.', intro: 'Poškodené čelné sklo riešime výmenou vhodného dielu a dôslednou montážou, aby vozidlo mohlo opäť bezpečne slúžiť.', details: ['Posúdenie poškodenia', 'Demontáž poškodeného skla', 'Montáž nového čelného skla'], image: '/images/workshop-exterior.webp', imageAlt: 'Vozidlá pred autoservisom Original Cars', icon: 'windshield' },
  { slug: 'dsg-a-opravy-prevodoviek', title: 'DSG a opravy prevodoviek', short: 'Servis DSG aj riešenie problémov s prevodovkami.', intro: 'Pri problémoch s radením najprv preveríme stav prevodovky a navrhneme primeraný servis alebo opravu.', details: ['Diagnostika problémov s radením', 'Servis DSG prevodoviek', 'Opravy prevodoviek podľa zisteného stavu'], image: '/images/workshop-interior.webp', imageAlt: 'Servis vozidla v autoservise Original Cars', icon: 'gearbox' },
  { slug: 'odtahova-sluzba', title: 'Odťahová služba', short: 'Pomoc s prepravou nepojazdného vozidla do servisu.', intro: 'Keď sa vozidlo nevie dostať do servisu vlastnou silou, dohodneme s vami možnosti odťahu a ďalší postup.', details: ['Dohoda odťahu telefonicky', 'Preprava vozidla do servisu', 'Nadväzujúca kontrola vozidla'], image: '/images/workshop-exterior.webp', imageAlt: 'Areál autoservisu Original Cars v Partizánskom', icon: 'towing' },
  { slug: 'dekarbonizacia-bg-a-prisady', title: 'BG dekarbonizácia a prísady', short: 'Starostlivosť o motor a predaj prísad do palív.', intro: 'Ponúkame dekarbonizáciu motora BG a vhodné prísady do palív. O konkrétnom použití vám poradíme podľa vozidla a jeho stavu.', details: ['Dekarbonizácia motora BG', 'Predaj prísad do palív', 'Odporúčanie vhodného postupu'], image: '/images/bg-additives.webp', imageAlt: 'Produkty BG pre starostlivosť o motor', icon: 'engine' },
  { slug: 'nastavenie-svetlometov', title: 'Nastavenie svetlometov', short: 'Presné nastavenie pre dobrý výhľad a bezpečnú jazdu.', intro: 'Správne nastavené svetlomety zlepšujú výhľad vodiča a zároveň neoslňujú ostatných účastníkov premávky.', details: ['Kontrola smerovania svetlometov', 'Nastavenie výšky a sklonu', 'Záverečná kontrola'], image: '/images/geometry-equipment.webp', imageAlt: 'Moderné servisné vybavenie', icon: 'lights' },
];

export const getService = (slug: string) => services.find((service) => service.slug === slug);
